"use strict";

const INSTITUTION_TYPES = [
  "University / Higher Education Institution",
  "Research Institute / Centre",
  "Government / Public Sector Agency",
  "Science Granting Council / Research Funder",
  "Innovation Agency / Technology Hub/Incubator",
  "Civil Society / NGO",
  "International Organisation / Multilateral Body",
  "Private Sector / Industry",
  "Research & Innovation Management Associations",
  "Independent / Consultant",
  "Other",
];

const COUNTRIES = [
  "Algeria",
  "Angola",
  "Benin",
  "Botswana",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cameroon",
  "Central African Republic",
  "Chad",
  "Comoros",
  "Democratic Republic of the Congo",
  "Djibouti",
  "Egypt",
  "Equatorial Guinea",
  "Eritrea",
  "Eswatini",
  "Ethiopia",
  "Gabon",
  "Gambia",
  "Ghana",
  "Guinea",
  "Guinea-Bissau",
  "Ivory Coast",
  "Kenya",
  "Lesotho",
  "Liberia",
  "Libya",
  "Madagascar",
  "Malawi",
  "Mali",
  "Mauritania",
  "Mauritius",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Niger",
  "Nigeria",
  "Rwanda",
  "Sao Tome and Principe",
  "Senegal",
  "Seychelles",
  "Sierra Leone",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Sudan",
  "Tanzania",
  "Togo",
  "Tunisia",
  "Uganda",
  "Zambia",
  "Zimbabwe",
];

const INDIVIDUAL_ROLES = [
  "Knowledge Consumer",
  "Knowledge Contributor",
  "Working Group Member",
  "Working Group Lead / Facilitator",
  "Mentor",
  "Mentee",
  "Event Organiser / Host",
  "Reviewer / Expert Advisor",
  "Institutional Representative",
  "Observer",
];

module.exports = {
  INSTITUTION_TYPES,
  COUNTRIES,
  INDIVIDUAL_ROLES,
};
